--
INSERT INTO ABOGADO_ENTITY (ID, NOMBRE, APELLIDO, ACTIVO, ESPECIALIDAD) VALUES (00001, 'María', 'Estupiñan', TRUE, 'Familia)
INSERT INTO ABOGADO_ENTITY (ID, NOMBRE, APELLIDO, ACTIVO, ESPECIALIDAD) VALUES (00002, 'Pedro', 'Pascal', True, 'Penalista')
INSERT INTO ABOGADO_ENTITY (ID, NOMBRE, APELLIDO, ACTIVO, ESPECIALIDAD) VALUES (00003, 'Carmen', 'Ruiz', False, 'Laboral')
